// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface CustomScript {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  header_script?: string;
  footer_script?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface HomePage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  hero_badge?: string;
  hero_bg_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hero_headline?: string;
  hero_accent_text?: string;
  hero_subheadline?: string;
  hero_primary_btn_text?: string;
  hero_primary_btn_url?: string;
  hero_secondary_btn_text?: string;
  hero_secondary_btn_url?: string;
  stat1_value?: string;
  stat1_label?: string;
  stat2_value?: string;
  stat2_label?: string;
  stat3_value?: string;
  stat3_label?: string;
  vehicles_tag?: string;
  vehicles_title?: string;
  vehicles_description?: string;
  why_tag?: string;
  why_title?: string;
  why_description?: string;
  cta_title?: string;
  cta_description?: string;
  cta_button_text?: string;
  cta_button_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  subtitle?: string;
  sections?: { "section_tag"?: string | null; "section_title"?: string | null; "section_layout"?: "hero" | "full-width" | "split-image-right" | "split-image-left" | "cta-banner" | null; "section_width"?: "default" | "reading" | "narrow" | "full" | null; "content"?: string | null; "button_text"?: string | null; "button_url"?: string | null; "secondary_button_text"?: string | null; "secondary_button_url"?: string | null; "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } | null }[];
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Vehicle {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  make: string;
  model: string;
  year: number;
  price?: number;
  mileage?: number;
  fuel_type?: string;
  transmission?: string;
  short_description?: string;
  is_featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    custom_scripts: CustomScript;
    home_page: HomePage;
    pages: Page;
    vehicles: Vehicle;
  }
}